name: agrilab_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  fl_chart: ^0.70.2
  google_sign_in: ^6.3.0
  flutter_secure_storage: ^9.2.4
  provider: ^6.1.2
  path_provider: ^2.1.5
  url_launcher: ^6.3.1
  app_links: ^6.4.0
  csv: ^6.0.0
  cupertino_icons: ^1.0.8
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
    - lib/assets/local_data/WSWMD_Trends-1m_Trends_1m__Trends-1m_Trends_1m_250309.csv
    - lib/assets/local_data/bquxjob_45fb5ac2_19622f4d8f5.csv

