name: agrilab_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  csv: ^6.0.0
  provider: ^6.1.4
  syncfusion_flutter_charts: ^29.1.38
  material_charts: ^0.0.26



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/AGT Logo.webp
    - lib/assets/data/bquxjob_72d2de2_1964f8a64a8.csv
    - lib/assets/data/bquxjob_72d2de2_1964f8a64a8_copy.csv
